//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATruckingPayroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int StageDesID { get; set; }
    
        public virtual StageDesc StageDesc { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Driver Driver1 { get; set; }
    }
}
